Fix unique_id code to use || instead of :
: is used in the SITE_URL, so it's a lousy delimiter. Switching
delimiters will fix this issue:

Traceback (most recent call last):
  File
"/data/input/src/input.mozilla.org/input/vendor/src/django/django/core/management/base.py",
line 222, in run_from_argv
    self.execute(*args, **options.__dict__)
  File
"/data/input/src/input.mozilla.org/input/vendor/src/django/django/core/management/base.py",
line 255, in execute
    output = self.handle(*args, **options)
  File
"/data/input/src/input.mozilla.org/input/fjord/translations/management/commands/translation_sync.py",
line 22, in handle
    system.pull_translations()
  File
"/data/input/src/input.mozilla.org/input/fjord/translations/models.py",
line 595, in pull_translations
    id_ = GengoJob.unique_id_to_id(comp['custom_data'])
  File
"/data/input/src/input.mozilla.org/input/fjord/translations/models.py",
line 312, in unique_id_to_id
    return int(parts[2])
ValueError: invalid literal for int() with base 10: 'GengoJob'